let abuse = ["ABE MERI BAR SUN HIZDA KII AULAD TERI MAAA KIIC HUT MERIA LUND",
    "BHOSDE KA ...TERI MAA CHODH CHODH KR TUJHE PAIDA KIYA H OR AJ TU",
    "APNA BAP SE PANGA LE RHA H..RUK TERI GATATE MAA KOO CHODHTA HU",
    "YEHI PR MADA CHODH BHOSDE KA KUUTA HIZDA KII PAIDAISDH TU TAATA",
    "CHATNA VALA KUUTAA HA I SALA RAND KII PAIDAISH MADA CHODH TERI",
    "MAAA KII CHUT MIA SE KHOON NIKALDUNGA YEHI PR RUKA BHOSDE KA AGR",
    "THIMMAT HAI TJHE MAI..TERI MAAA OR BHEN KO MERA PAS BHEJ ..ACHA",
    "PAISE DILVADUNGA RUK JA MADACHODH....SALA GANDU APNA BAP S PANGE",
    "LE RHA H...ABE MERI BAR SUN HIZDA KII AULAD TERI MAAA KIIC HUT",
    "MERIA LUND BHOSDE KA ...TERI MAA CHODH CHODH KR TUJHE PAIDA KIYA H",
    "OR AJ TU APNA BAP SE PANGA LE RHA H..RUK TERI GATATE MAA KOO",
    "CHODHTA HU YEHI PR MADA CHODH BHOSDE KA KUUTA HIZDA KII PAIDAISDH",
    "TU TAATA CHATNA VALA KUUTAA HA I SALA RAND KII PAIDAISH MADA CHODH",
    "TERI MAAA KII CHUT MIA SE KHOON NIKALDUNGA YEHI PR RUKA",
    "BHOSDE KA AGR THIMMAT HAI TJHE MAI..TERI MAAA OR BHEN KO MERA PAS",
    "BHEJ ..ACHA PAISE DILVADUNGA RUK JA MADACHODH....SALA GANDU APNA",
    "BAP S PANGE LE RHA H...ABE MERI BAR SUN HIZDA KII AULAD TERI MAAA",
    "KIIC HUT MERIA LUND BHOSDE KA ...TERI MAA CHODH CHODH KR TUJHE",
    "PAIDA KIYA H OR AJ TU APNA BAP SE PANGA LE RHA H..RUK TERI GATATE",
    "MAA KOO CHODHTA HU YEHI PR MADA CHODH BHOSDE KA KUUTA HIZDA KII",
    "PAIDAISDH TU TAATA CHATNA VALA KUUTAA HA I SALA RAND KII PAIDAISH",
    "MADA CHODH TERI MAAA KII CHUT MIA SE KHOON NIKALDUNGA YEHI PR RUKA",
    "BHOSDE KA AGR THIMMAT HAI TJHE MAI..TERI MAAA OR BHEN KO",
    "MERA PAS BHEJ ..ACHA PAISE DILVADUNGA RUK JA MADACHODH....SALA",
    "GANDU APNA BAP S PANGE LE RHA H...ABE MERI BAR SUN HIZDA KII AULAD",
    "TERI MAAA KIIC HUT MERIA LUND BHOSDE KA ...TERI MAA CHODH",
    "CHODH KR TUJHE PAIDA KIYA H OR AJ TU APNA BAP SE PANGA LE RHA",
    "H..RUK TERI GATATE MAA KOO CHODHTA HU YEHI PR MADA CHODH BHOSDE",
    "KA KUUTA HIZDA KII PAIDAISDH TU TAATA CHATNA VALA KUUTAA HA I SALA",
    "RAND KII PAIDAISH MADA CHODH TERI MAAA KII CHUT MIA SE",
    "KHOON NIKALDUNGA YEHI PR RUKA BHOSDE KA AGR THIMMAT HAI TJHE",
    "MAI..TERI MAAA OR BHEN KO MERA PAS BHEJ ..ACHA PAISE DILVADUNGA",
    "RUK JA MADACHODH....SALA GANDU APNA BAP S PANGE LE RHA H...",
    "ABE MERI BAR SUN HIZDA KII AULAD TERI MAAA KIIC HUT MERIA LUND BHOSDE",
    "KA ...TERI MAA CHODH CHODH KR TUJHE PAIDA KIYA H OR AJ TU APNA BAP",
    "SE PANGA LE RHA H..RUK TERI GATATE MAA KOO CHODHTA HU YEHI",
    "PR MADA CHODH BHOSDE KA KUUTA HIZDA KII PAIDAISDH TU TAATA CHATNA",
    "VALA KUUTAA HA I SALA RAND KII PAIDAISH MADA CHODH TERI MAAA KII",
    "CHUT MIA SE KHOON NIKALDUNGA YEHI PR RUKA BHOSDE KA AGR THIMMAT",
    "HAI TJHE MAI..TERI MAAA OR BHEN KO MERA PAS BHEJ ..ACHA PAISE",
    "DILVADUNGA RUK JA MADACHODH....SALA GANDU APNA BAP S PANGE LE",
    "RHA H...ABE MERI BAR SUN HIZDA KII AULAD TERI MAAA KIIC HUT MERIA",
    "LUND BHOSDE KA ...TERI MAA CHODH CHODH KR TUJHE PAIDA KIYA H",
    "OR AJ TU APNA BAP SE PANGA LE RHA H..RUK TERI GATATE MAA KOO",
    "CHODHTA HU YEHI PR MADA CHODH BHOSDE KA KUUTA HIZDA KII PAIDAISDH TU",
    "TAATA CHATNA VALA KUUTAA HA I SALA RAND KII PAIDAISH MADA",
    "CHODH TERI MAAA KII CHUT MIA SE KHOON NIKALDUNGA YEHI PR RUKA BHOSDE",
    "KA AGR THIMMAT HAI TJHE MAI..TERI MAAA OR BHEN KO MERA PAS",
    "BHEJ ..ACHA PAISE DILVADUNGA RUK JA MADACHODH....",
    "SALA GANDU APNA BAP S PANGE LE RHA H...ABE MERI BAR SUN HIZDA KII AULAD",
    "TERI MAAA KIIC HUT MERIA LUND BHOSDE KA ...TERI MAA CHODH CHODH KR",
    "TUJHE PAIDA KIYA H OR AJ TU APNA BAP SE PANGA LE RHA H..RUK TERI",
    "GATATE MAA KOO CHODHTA HU YEHI PR MADA CHODH BHOSDE KA KUUTA HIZDA",
    "KII PAIDAISDH TU TAATA CHATNA VALA KUUTAA HA I SALA RAND KII",
    "PAIDAISH MADA CHODH TERI MAAA KII CHUT MIA SE KHOON NIKALDUNGA YEHI PR",
    "RUKA BHOSDE KA AGR THIMMAT HAI TJHE MAI..TERI MAAA OR BHEN KO",
    "MERA PAS BHEJ ..ACHA PAISE DILVADUNGA RUK JA MADACHODH....",
    "SALA GANDU APNA BAP S PANGE LE RHA H..."]

let string = `ABE MERI BAR SUN HIZDA KII AULAD TERI MAAA KIIC HUT MERIA LUND
BHOSDE KA ...TERI MAA CHODH CHODH KR TUJHE PAIDA KIYA H OR AJ TU
APNA BAP SE PANGA LE RHA H..RUK TERI GATATE MAA KOO CHODHTA HU
YEHI PR MADA CHODH BHOSDE KA KUUTA HIZDA KII PAIDAISDH TU TAATA
CHATNA VALA KUUTAA HA I SALA RAND KII PAIDAISH MADA CHODH TERI
MAAA KII CHUT MIA SE KHOON NIKALDUNGA YEHI PR RUKA BHOSDE KA AGR
THIMMAT HAI TJHE MAI..TERI MAAA OR BHEN KO MERA PAS BHEJ ..ACHA
PAISE DILVADUNGA RUK JA MADACHODH....SALA GANDU APNA BAP S PANGE
LE RHA H...ABE MERI BAR SUN HIZDA KII AULAD TERI MAAA KIIC HUT
MERIA LUND BHOSDE KA ...TERI MAA CHODH CHODH KR TUJHE PAIDA KIYA H
OR AJ TU APNA BAP SE PANGA LE RHA H..RUK TERI GATATE MAA KOO
CHODHTA HU YEHI PR MADA CHODH BHOSDE KA KUUTA HIZDA KII PAIDAISDH
TU TAATA CHATNA VALA KUUTAA HA I SALA RAND KII PAIDAISH MADA CHODH
TERI MAAA KII CHUT MIA SE KHOON NIKALDUNGA YEHI PR RUKA
BHOSDE KA AGR THIMMAT HAI TJHE MAI..TERI MAAA OR BHEN KO MERA PAS
BHEJ ..ACHA PAISE DILVADUNGA RUK JA MADACHODH....SALA GANDU APNA
BAP S PANGE LE RHA H...ABE MERI BAR SUN HIZDA KII AULAD TERI MAAA
KIIC HUT MERIA LUND BHOSDE KA ...TERI MAA CHODH CHODH KR TUJHE
PAIDA KIYA H OR AJ TU APNA BAP SE PANGA LE RHA H..RUK TERI GATATE
MAA KOO CHODHTA HU YEHI PR MADA CHODH BHOSDE KA KUUTA HIZDA KII
PAIDAISDH TU TAATA CHATNA VALA KUUTAA HA I SALA RAND KII PAIDAISH
MADA CHODH TERI MAAA KII CHUT MIA SE KHOON NIKALDUNGA YEHI PR RUKA
BHOSDE KA AGR THIMMAT HAI TJHE MAI..TERI MAAA OR BHEN KO
MERA PAS BHEJ ..ACHA PAISE DILVADUNGA RUK JA MADACHODH....SALA
GANDU APNA BAP S PANGE LE RHA H...ABE MERI BAR SUN HIZDA KII AULAD
TERI MAAA KIIC HUT MERIA LUND BHOSDE KA ...TERI MAA CHODH
CHODH KR TUJHE PAIDA KIYA H OR AJ TU APNA BAP SE PANGA LE RHA
H..RUK TERI GATATE MAA KOO CHODHTA HU YEHI PR MADA CHODH BHOSDE
KA KUUTA HIZDA KII PAIDAISDH TU TAATA CHATNA VALA KUUTAA HA I SALA
RAND KII PAIDAISH MADA CHODH TERI MAAA KII CHUT MIA SE
KHOON NIKALDUNGA YEHI PR RUKA BHOSDE KA AGR THIMMAT HAI TJHE
MAI..TERI MAAA OR BHEN KO MERA PAS BHEJ ..ACHA PAISE DILVADUNGA
RUK JA MADACHODH....SALA GANDU APNA BAP S PANGE LE RHA H...
ABE MERI BAR SUN HIZDA KII AULAD TERI MAAA KIIC HUT MERIA LUND BHOSDE
KA ...TERI MAA CHODH CHODH KR TUJHE PAIDA KIYA H OR AJ TU APNA BAP
SE PANGA LE RHA H..RUK TERI GATATE MAA KOO CHODHTA HU YEHI
PR MADA CHODH BHOSDE KA KUUTA HIZDA KII PAIDAISDH TU TAATA CHATNA
VALA KUUTAA HA I SALA RAND KII PAIDAISH MADA CHODH TERI MAAA KII
CHUT MIA SE KHOON NIKALDUNGA YEHI PR RUKA BHOSDE KA AGR THIMMAT
HAI TJHE MAI..TERI MAAA OR BHEN KO MERA PAS BHEJ ..ACHA PAISE
DILVADUNGA RUK JA MADACHODH....SALA GANDU APNA BAP S PANGE LE
RHA H...ABE MERI BAR SUN HIZDA KII AULAD TERI MAAA KIIC HUT MERIA
LUND BHOSDE KA ...TERI MAA CHODH CHODH KR TUJHE PAIDA KIYA H
OR AJ TU APNA BAP SE PANGA LE RHA H..RUK TERI GATATE MAA KOO
CHODHTA HU YEHI PR MADA CHODH BHOSDE KA KUUTA HIZDA KII PAIDAISDH TU
TAATA CHATNA VALA KUUTAA HA I SALA RAND KII PAIDAISH MADA
CHODH TERI MAAA KII CHUT MIA SE KHOON NIKALDUNGA YEHI PR RUKA BHOSDE
KA AGR THIMMAT HAI TJHE MAI..TERI MAAA OR BHEN KO MERA PAS
BHEJ ..ACHA PAISE DILVADUNGA RUK JA MADACHODH....
SALA GANDU APNA BAP S PANGE LE RHA H...ABE MERI BAR SUN HIZDA KII AULAD
TERI MAAA KIIC HUT MERIA LUND BHOSDE KA ...TERI MAA CHODH CHODH KR
TUJHE PAIDA KIYA H OR AJ TU APNA BAP SE PANGA LE RHA H..RUK TERI
GATATE MAA KOO CHODHTA HU YEHI PR MADA CHODH BHOSDE KA KUUTA HIZDA
KII PAIDAISDH TU TAATA CHATNA VALA KUUTAA HA I SALA RAND KII
PAIDAISH MADA CHODH TERI MAAA KII CHUT MIA SE KHOON NIKALDUNGA YEHI PR
RUKA BHOSDE KA AGR THIMMAT HAI TJHE MAI..TERI MAAA OR BHEN KO
MERA PAS BHEJ ..ACHA PAISE DILVADUNGA RUK JA MADACHODH....
SALA GANDU APNA BAP S PANGE LE RHA H...
`
console.log(string.length)